const STORAGE_KEYS = {
  RF_USER_STORE: "RF_USER_STORE",
  RF_TOKEN: "RF_TOKEN",
  RF_USER_EMAIL: "RF_USER_EMAIL",
  RF_USER: "RF_USER",
  RF_USER_LISTINGS: "RF_USER_LISTINGS",
}

export default STORAGE_KEYS
