const STORAGE_KEYS = {
  RF_USER_STORE: "RF_USER_STORE",
  RF_TOKEN: "RF_TOKEN",
  RF_USER_EMAIL: "RF_USER_EMAIL",
  RF_USER: "RF_USER",
  RF_USER_LISTINGS: "RF_USER_LISTINGS",
  RF_LISTINGS: "RF_LISTINGS",
  RF_USER_FAVORITES: "RF_USER_FAVORITES",
  RF_USER_INTERESTS: "RF_USER_INTERESTS",
  RF_USER_MESSAGES: "RF_USER_MESSAGES",
  RF_USER_CONVERSATIONS: "RF_USER_CONVERSATIONS",
}

export default STORAGE_KEYS
