name: CI/CD
on:
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'npm'
    
    # 1. install node modules 
    - run: npm install
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      with:
        envkey_NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        envkey_NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
        directory: ./
        file_name: .env
        fail_on_empty: false
        sort_keys: false
    # 2. just build the application for now since we don't really have any
    #    tests. 
    - run: npm run build
      # env:
      #   CI: false
      
    
    # linting/airbnb !?

